version: "3.3"

services:
  traefik:
    image: traefik:v2.9
    container_name: as-traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" # Enable the Trafik dashboard
      - "--providers.docker=true" # Tell Traefik to discover containers using the Docker API
      - "--providers.docker.exposedbydefault=false" # Create routing configuration only for containers with traefik.enable=true
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authelia@docker"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_conf.yml:/etc/traefik/dynamic_conf/conf.yml:ro"
      - "./certs:/etc/certs"

  authelia:
    image: authelia/authelia:4.37
    container_name: as-authelia
    restart: unless-stopped
    volumes:
      - ./authelia:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`authelia.${DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.${DOMAIN}"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    expose:
      - 9091
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - openldap

  whoami:
    image: traefik/whoami
    container_name: as-whoami
    restart: unless-stopped
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.page1.rule=Host(`page1.${DOMAIN}`)"
      - "traefik.http.routers.page1.entrypoints=websecure"
      - "traefik.http.routers.page1.middlewares=authelia@docker"
      - "traefik.http.services.page1.loadbalancer.server.port=80"

  whoami2:
    image: traefik/whoami
    container_name: as-whoami2
    restart: unless-stopped
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.page2.rule=Host(`page2.${DOMAIN}`)"
      - "traefik.http.routers.page2.entrypoints=websecure"
      - "traefik.http.routers.page2.middlewares=authelia@docker"
      - "traefik.http.services.page2.loadbalancer.server.port=80"

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    restart: unless-stopped
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "LocalTest Inc."
      LDAP_DOMAIN: "${DOMAIN}"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "password" # login 'cn=admin,dc=localtest,dc=me'
      LDAP_TLS: "false"
    volumes:
      - './ldif-custom:/container/service/slapd/assets/config/bootstrap/ldif/custom'
      - './volume-ldap:/var/lib/ldap'
      - './volume-slapd:/etc/ldap/slapd.d'
    command: "--copy-service --loglevel debug"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    expose:
      - "80"
    depends_on:
      - openldap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ldap.rule=Host(`ldap.${DOMAIN}`)"
      - "traefik.http.routers.ldap.entrypoints=websecure"
      - "traefik.http.routers.ldap.middlewares=authelia@docker"
      - "traefik.http.services.ldap.loadbalancer.server.port=80"