###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

default_2fa_method: totp
totp:
  issuer: localtest.me
webauthn:
  disable: true
duo_api:
  disable: true

authentication_backend:
  # file:
    # path: /config/users_database.yml
  ldap:
    implementation: custom
    url: ldap://openldap
    timeout: 5s
    base_dn: DC=localtest,DC=me
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=account)) # To allow sign in both with username and email
    groups_filter: (&(member={dn})(objectClass=groupOfNames))
    group_name_attribute: cn
    username_attribute: uid
    mail_attribute: mail
    display_name_attribute: description
    user: cn=admin,dc=localtest,dc=me
    password: password
    start_tls: false

access_control:
  default_policy: deny # deny access for subdomains not defined in the rules section 
  rules:
    - domain: page1.localtest.me
      policy: one_factor
      subject:
        - 'group:page1'
        - 'group:admin'
    - domain: page2.localtest.me
      policy: one_factor
      subject:
        - 'group:page2'
        - 'group:admin'
    - domain: ['traefik.localtest.me']
      policy: one_factor
      subject:
        - 'group:admin'
    - domain: ['ldap.localtest.me']
      policy: bypass


session:
  name: authelia_session
  secret: unsecure_session_secret
  expiration: 1M
  inactivity: 1M
  remember_me_duration: 1M
  domain: localtest.me  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300 # 5 minutes

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt